#!/bin/sh
set -e
# SoX Resampler Library       Copyright (c) 2007-13 robs@users.sourceforge.net
# Licence for this file: LGPL v2.1                  See LICENCE for details.

# Sanity-check of library installed on unix-like system

# Where are the example source files:
src=$1
test x$src = x && src=/usr/local/share/doc/libsoxr/examples

dir="$(dirname $(readlink -f $0))"
$dir/inst-check-soxr $src
$dir/inst-check-soxr-lsr $src
