#!/bin/bash
set -e

# SoX Resampler Library       Copyright (c) 2007-14 robs@users.sourceforge.net
# Licence for this file: LGPL v2.1                  See LICENCE for details.

len=8
#vg="valgrind --leak-check=full --show-reachable=yes"



# Exercise example 1:
$vg ./1-single-block



# Check that examples 2-4 can convert 96k<->44k1 and that results are same for each:
ir=96000
or=44100
for i in 1 2; do
  prev=""
  sox -r $ir -n 0.f32 synth $len sin 0+`expr $ir / 2`
  for f in `find . -type f -executable -name "[2-4]*"`; do
    $vg $f $ir $or < 0.f32 > $f.f32
    test x$prev != x && cmp $f.f32 $prev
    prev=$f.f32
  done
  or=96000
  ir=44100
done
rm *.f32



# Check conversion between differing I/O types, but no rate-change:
for i in 1 2 3; do
  prev=""
  sox -n -c $i 0.f32 synth $len gain -.1
  ./3-options-input-fn 1 1 $i 0 2 < 0.f32 | ./3-options-input-fn 1 1 $i 2 0 > 1.f32
  cmp [01].f32
done
rm *.f32


# Exercise VR making sure that varied internal stage reconfigurations occur:
rm -f ?.png
for n in 0 1 2 3; do
  $vg ./5-variable-rate $n | sox -tf32 -r44100 -c1 - -n spectrogram -z130 -hwd -o $n.png -X 50
  vg=""
done
