#!/bin/bash
set -e

# SoX Resampler Library       Copyright (c) 2007-14 robs@users.sourceforge.net
# Licence for this file: LGPL v2.1                  See LICENCE for details.

# Tests rate conversion time and generates spectrograms for qualities 0..7 & variable-rate.



rm -f *.png *.wav
tool=./3-options-input-fn

spec="spectrogram -z180 -Z-20 -wd -ho"
ext=f32; e=0
ext=f64; e=1
c=2
q1=4; q2=4
q1=0; q2=7

rates=48000
rates="48000 77773 96000"

for rate0 in $rates; do

rate1=$rate0
rate2=44100

for n in 1 2; do

rate1n=`expr $rate1 / 2`



# Measure time to convert a 5-minute file:

#: << :
sox -r $rate1 -n -c $c 0.$ext synth 5: sin 0:$rate1n gain -1

for q in `seq $q1 $q2`; do
	echo $rate1 '-->' $rate2 c=$c q=$q
       	time $tool $rate1 $rate2 $c $e $e $q < 0.$ext > /dev/null;
done
echo $rate1 '-->' $rate2 c=$c q=v
time $tool $rate1 $rate2 $c $e $e 4 20 < 0.$ext > /dev/null
:



# Convert sweep, for spectrogram:

sox -r $rate1 -n -c $c 0.$ext synth 8 sin 0:$rate1n gain -1

for q in `seq $q1 $q2`; do
	f=$rate1-$rate2-a-$q
	$tool $rate1 $rate2 $c $e $e $q  0 < 0.$ext | sox -c$c -r$rate2 -t $ext - -n $spec $f.png
done
f=$rate1-$rate2-a-v
$tool $rate1 $rate2 $c $e $e 4 20 < 0.$ext | sox -c$c -r$rate2 -t $ext - -n $spec $f.png



# Convert impulse, for spectrogram:

#: << :
sox -r $rate1 -n 0.$ext synth 1s sq pad .03 .03  gain -1

for q in `seq $q1 $q2`; do
	f=$rate1-$rate2-b-$q
	$tool $rate1 $rate2 1 $e $e $q  0 < 0.$ext | sox -c1 -r$rate2 -t $ext - $f.wav $spec $f.png -X 2000
done
f=$rate1-$rate2-b-v
$tool $rate1 $rate2 1 $e $e 4 20 < 0.$ext | sox -c1 -r$rate2 -t $ext - $f.wav $spec $f.png -X 2000

# Combine impuse responses into multi-channel file (for inspection in Audacity):
sox -M $rate1-$rate2-b-?.wav $rate1-$rate2.wav

rm $rate1-$rate2-b-?.wav
:

rate1=44100
rate2=$rate0

done
done

rm 0.$ext
