#!/bin/bash
set -e

# SoX Resampler Library       Copyright (c) 2007-15 robs@users.sourceforge.net
# Licence for this file: LGPL v2.1                  See LICENCE for details.

../../tests/bandwidth-test
../../tests/eg-test
../../tests/io-test
../../tests/large-ratio-test
../../tests/phase-test
../../tests/q-test
../../tests/time-test
